require 'rspec/core/rake_task'

namespace :puppet do 
  desc 'Run puppet-lint'
  task :lint do
    sh %{bundle exec puppet-lint --with-filename --fail-on-warnings --no-documentation-check --no-double_quoted_strings-check --no-quoted_booleans-check modules}
  end
  desc 'Generate puppet docs'
  task :doc  do
    sh %{bundle exec puppet strings --modulepath modules} 
  end
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'modules/*/spec/*/*_spec.rb'
  t.verbose = false
end



